name: realestate
description: A New Flutter Project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.0.2
  flutter_screenutil: ^5.9.3
  go_router: ^7.1.0
  flutter_svg: ^2.0.9
  animations: ^2.0.8
  gap:
  google_maps_flutter: ^2.9.0
  riverpod_annotation: ^2.3.4
  flutter_map: 4.0.0
  latlong2:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.2

  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  built_value_generator: ^8.4.1
  riverpod_generator:

  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/logo.png
  color: "5E92F3"
  android_disable_fullscreen: true

flutter:
  generate: true

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/
#    - assets/images/3.0x/logo.png
#    - assets/images/login.png
#    - assets/images/signup.png

  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/EuclidCircularABold.ttf
          weight: 700
        - asset: assets/fonts/EuclidCircularASemiBold.ttf
          weight: 600
        - asset: assets/fonts/EuclidCircularAMedium.ttf
          weight: 500
        - asset: assets/fonts/EuclidCircularARegular.ttf
          weight: 400
